"""Spectra domain entities — Layer 1 of Clean Architecture (zero spectra-internal imports).

This is the innermost layer of Spectra's Clean Architecture. It contains:

- **Literal type aliases** (``enums.py``): ``Severity``, ``Dimension``, ``Grade``,
  ``AgentRole``, and ``PipelineState`` — using ``Literal`` for JSON-safe enums.
- **Error hierarchy** (``errors.py``): ``SpectraError`` descriptors with retry
  metadata (SPEC-001 through SPEC-009), plus ``AgentError``, ``GitError``, and
  ``SpectraRetryError`` exception classes.
- **Frozen Pydantic models** (``models.py``): All domain objects are immutable
  (``frozen=True``). Key models include ``Finding`` (dedupable by file/line/dim),
  ``ScoreCard``, ``AnalysisReport``, ``Codebase``, and ``TokenBudget``.

**Dependency rule**: This layer imports NOTHING from the ``spectra`` package.
All other layers depend on entities, but entities depend on no one.

All public symbols are re-exported here via ``__all__`` for convenient access
from outer layers (e.g. ``from spectra.entities import Finding, ScoreCard``).
"""

from spectra.entities.audit import (
    FORBIDDEN_PAYLOAD_KEYS,
    AuditEvent,
    AuditEventType,
    AuditTarget,
    Identity,
    IdentityConfidence,
    IdentitySource,
    new_event_id,
)
from spectra.entities.disclaimer import (
    DISCLAIMER_TEXT,
    DISCLAIMER_URL,
    disclaimer_payload,
)
from spectra.entities.enums import (
    AgentRole,
    Dimension,
    Grade,
    PipelineState,
    SchemaVersion,
    Severity,
)
from spectra.entities.errors import (
    ERRORS,
    AgentError,
    BudgetExceededError,
    GitError,
    SecretDetectedError,
    SpectraError,
    SpectraRetryError,
    strip_code_fence,
)
from spectra.entities.models import (
    DEFAULT_DIMENSION_SCORE,
    EXCELLENT_SCORE,
    MIN_CONFIDENCE,
    PASSING_SCORE,
    AgentContext,
    AgentOutput,
    AgentRunConfig,
    AnalysisReport,
    AnalysisRequest,
    Approver,
    BatchCacheKey,
    BatchHandle,
    BatchPrompt,
    BatchRequestItem,
    BatchResult,
    BatchResultItem,
    CacheEntry,
    CacheSecret,
    CacheStats,
    CacheUsage,
    Classification,
    Codebase,
    DimensionScore,
    EffortLevel,
    EmptyPolicy,
    FileLocation,
    Finding,
    ModelId,
    NotifierMessage,
    Policy,
    RepoCacheKey,
    ReportSummary,
    ScoreCard,
    SecretFinding,
    SeverityGate,
    TokenBudget,
    ValidationStatus,
    Violation,
    ViolationKind,
    Waiver,
    compute_finding_signature,
    estimate_cache_savings,
    estimate_cost,
    score_to_grade,
)
from spectra.entities.receipt import ScanReceipt

__all__ = [
    "DEFAULT_DIMENSION_SCORE",
    "DISCLAIMER_TEXT",
    "DISCLAIMER_URL",
    "ERRORS",
    "EXCELLENT_SCORE",
    "FORBIDDEN_PAYLOAD_KEYS",
    "MIN_CONFIDENCE",
    "PASSING_SCORE",
    "AgentContext",
    "AgentError",
    "AgentOutput",
    "AgentRole",
    "AgentRunConfig",
    "AnalysisReport",
    "AnalysisRequest",
    "Approver",
    "AuditEvent",
    "AuditEventType",
    "AuditTarget",
    "BatchCacheKey",
    "BatchHandle",
    "BatchPrompt",
    "BatchRequestItem",
    "BatchResult",
    "BatchResultItem",
    "BudgetExceededError",
    "CacheEntry",
    "CacheSecret",
    "CacheStats",
    "CacheUsage",
    "Classification",
    "Codebase",
    "Dimension",
    "DimensionScore",
    "EffortLevel",
    "EmptyPolicy",
    "FileLocation",
    "Finding",
    "GitError",
    "Grade",
    "Identity",
    "IdentityConfidence",
    "IdentitySource",
    "ModelId",
    "NotifierMessage",
    "PipelineState",
    "Policy",
    "RepoCacheKey",
    "ReportSummary",
    "ScanReceipt",
    "SchemaVersion",
    "ScoreCard",
    "SecretDetectedError",
    "SecretFinding",
    "Severity",
    "SeverityGate",
    "SpectraError",
    "SpectraRetryError",
    "TokenBudget",
    "ValidationStatus",
    "Violation",
    "ViolationKind",
    "Waiver",
    "compute_finding_signature",
    "disclaimer_payload",
    "estimate_cache_savings",
    "estimate_cost",
    "new_event_id",
    "score_to_grade",
    "strip_code_fence",
]
